language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
addons:
  apt:
    packages:
    - aspell-en
script:
- npm install alex --global
- bash scripts/language-check.sh
- bundle exec middleman build
